---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable
cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test

jobs:
  fail_fast: true

  include:
    - stage: "Quality"
      name: "Lint JS/TS"
      script: time ./run yarn lint:js
    - name: "Lint Templates"
      script: time ./run yarn lint:hbs
    - name: "Lint Styles"
      script: time ./run yarn lint:sass
    - name: "Check Types"
      script: time ./run yarn tsc

    - stage: "Tests"
      name: "Unit Tests"
      script: time ./run yarn test:named Unit
    - name: "Helper Tests"
      script: time ./run yarn test:named Helper
    - name: "Integration Tests"
      script: time ./run yarn test:named Integration
    - name: "Acceptance Tests"
      script: time ./run yarn test:named Acceptance
